---
- name: Setup BetonQuest Host
  hosts: beton_quest
  become: true
  roles:
    - role: base
      tags: [ base ]
    - role: nginx/core
      tags: [ nginx ]
    - role: reposilite
      tags: [ reposilite ]
